name: my_mobile_app
description: "Flutter assessment project."
publish_to: 'none'
version: 1.0.0+1

scripts: derry.yaml

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  bottom_sheet: ^4.0.0
  cached_network_image: ^3.2.3
  convex_bottom_bar: ^3.2.0
  device_preview: ^1.1.0
  dio: ^5.2.1+1
  dropdown_button2: ^2.3.9
  easy_debounce: ^2.0.3
  easy_localization: ^3.0.2
  envied: ^0.3.0+3
  envied_generator: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^15.1.0+1 
  flutter_native_splash: ^2.3.1
  flutter_secure_storage: ^8.0.0
  flutter_switch: ^0.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  loader_overlay: ^2.3.0
  logger: ^1.4.0
  meta: ^1.9.1
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_flavorizr: ^2.1.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.0
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0+1

# ================================================
#  FLAVORIZR SETUP
# ================================================
# If updating applicationId and bundleId, call this command
# fvm flutter pub run flutter_flavorizr -p ios:xcconfig,ios:buildTargets,ios:schema,ios:plist,android:buildGradle

# If updating app icons, call this command 
# fvm flutter pub run flutter_flavorizr -p ios:icons,android:icons
flavorizr:
  flavors:
    production:
      app:
        name: "Flutter BLoC Project"
        icon: "assets/app_icons/prod_icon.png"

      android:
        applicationId: "com.example.mymobileapp"

      ios:
        bundleId: "com.example.mymobileapp"

    development:
      app:
        name: "[DEV] Flutter BLoC Project"
        icon: "assets/app_icons/dev_icon.png"

      android:
        applicationId: "com.example.mymobileapp.development"

      ios:
        bundleId: "com.example.mymobileapp.development"

    staging:
      app:
        name: "[STA] Flutter BLoC Project"
        icon: "assets/app_icons/staging_icon.png"

      android:
        applicationId: "com.example.mymobileapp.staging"

      ios:
        bundleId: "com.example.mymobileapp.staging"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lang/
  fonts:
    - family:  Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Black.ttf
          weight: 900
        - asset: assets/fonts/mulish/Mulish-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/mulish/Mulish-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/mulish/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/mulish/Mulish-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/mulish/Mulish-Italic.ttf
          style: italic
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-SemiBoldItalic.ttf
          weight: 600
          style: italic
